version: '3'
services:

  #PHP Service
  rozh-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rozh-app
    container_name: rozh-app
    restart: unless-stopped
    tty: true
    ports:
        - "9000:3306"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - rozh-app-network

  #Nginx Service
  rozh-app-nginx:
    image: nginx:alpine
    container_name: rozh-app-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "9001:80"
      - "9002:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - rozh-app-network

  #MySQL Service
  rozh-app-db:
    image: mysql:8.0.33
    container_name: rozh-app-db
    restart: unless-stopped
    tty: true
    ports:
      - "9003:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: laravel
      SERVICE_TAGS: prod
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - rozh-app-network

#Docker Networks
networks:
  rozh-app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
