<?php


return [
    'APP_NAME' => env('APP_NAME'),

//    'HYPERPOST_API_URL' => env('HYPERPOST_API_URL'),
//    'HYPERPOST_TOKEN' => env('HYPERPOST_TOKEN'),
//    'HYPERPOST_ENCRYPT_CODE' => env('HYPERPOST_ENCRYPT_CODE'),


    'HYPERPOST_API_URL' => env('HYPERPOST_API_URL'),
    'HYPERPOST_USER_EMAIL' => env('HYPERPOST_USER_EMAIL'),
    'HYPERPOST_USER_PASSWORD' => env('HYPERPOST_USER_PASSWORD'),

    'TELEGRAM_CHAT_ID' => env('TELEGRAM_CHAT_ID'),

    'LOGO_MAIN' => env('LOGO_MAIN'),
    'LOGO_SMALL' => env('LOGO_SMALL'),
    'LOGO_LARGE' => env('LOGO_LARGE'),
];
