<?php


return [
    'APP_NAME' => env('APP_NAME'),
    'HYPERPOST_API_URL' => env('HYPERPOST_API_URL'),
    'HYPERPOST_TOKEN' => env('HYPERPOST_TOKEN'),
    'HYPERPOST_ENCRYPT_CODE' => env('HYPERPOST_ENCRYPT_CODE'),
];